# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
     
    # pod 'BlokID-iOS-Netset', :path => '../BlokID-iOS-Netset' 
    pod 'BlokID-iOS-Netset' 

end
